name: ${project.name}
main: net.enelson.soptelephones.SopTelephonesPlugin
version: ${project.version}
authors: [E_NeLsOn]
depend: [SopLib]
softdepend: [Vault]
api-version: 1.16
commands:
  soptelephones:
    usage: /soptelephones
    permission: soptelephones.admin
  phone:
    usage: /phone
  sms:
    usage: /sms <number> <message>
permissions:
  soptelephones.admin:
    default: op
